Update master_build.yml
Revert recent changes and add v prefix missing from version check

diff --git a/.github/workflows/master_build.yml b/.github/workflows/master_build.yml
--- a/.github/workflows/master_build.yml
+++ b/.github/workflows/master_build.yml
@@ -37,7 +37,8 @@ jobs:
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "Extracted version: $VERSION"
       
-      - name: Debug regex checks
+      - name: Check version pattern and merge
+        id: check_version
         run: |
           VERSION=${{ env.VERSION }}
           echo "Checking version pattern: $VERSION"
@@ -45,39 +46,7 @@ jobs:
             echo "Already on main branch. Skipping merge check."
             exit 0
           fi
-          
-          # Extract major, minor, patch, and suffix parts
-          MAJOR=${BASH_REMATCH[1]}
-          MINOR=${BASH_REMATCH[2]}
-          PATCH=${BASH_REMATCH[3]}
-          SUFFIX=${BASH_REMATCH[4]}
-          echo "Extracted Major: $MAJOR"
-          echo "Extracted Minor: $MINOR"
-          echo "Extracted Patch: $PATCH"
-          echo "Extracted Suffix: $SUFFIX"
-          
-          # Check full release version pattern
-          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Full release version pattern matched."
-          else
-            echo "Full release version pattern NOT matched."
-          fi
-
-          # Check pre-release version pattern
-          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-(a|b|rc)[0-9]+$ ]]; then
-            echo "Pre-release version pattern matched."
-          else
-            echo "Pre-release version pattern NOT matched."
-          fi
-
-          # Check if invalid or development version
-          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-(a|b|rc)[0-9]+$ ]]; then
-            echo "Version is invalid or a development version. Cancelling workflow."
-            exit 1
-          fi
-
-          # If it is a full release version, create a pull request to merge into main
-          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          if [[ $VERSION =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
             echo "Version is a full release. Creating pull request to merge into main."
             echo "## Check for existing PR"
             if gh pr list --head development --base main --state open --json number --jq .[0].number; then
@@ -87,11 +56,11 @@ jobs:
             echo "Creating new PR."
             gh pr create --title "Release $VERSION" --body "Merging development into main for release $VERSION" --base main --head development
             exit 1
-          fi
-
-          # If it is a pre-release version, proceed with pre-release build
-          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-(a|b|rc)[0-9]+$ ]]; then
+          if [[ $VERSION =~ ^v?[0-9]+\.[0-9]+\.[0-9]+-(a|b|rc)[0-9]+$ ]]; then
             echo "Version is a pre-release. Proceeding with pre-release build."
+          else
+            echo "Version is invalid or a development version. Cancelling workflow."
+            exit 1
           fi
         shell: bash
         env:
@@ -176,6 +145,8 @@ jobs:
           
       - name: Zip artifact for deployment
         run: Compress-Archive -Path "MenyooSP/*" -DestinationPath "MenyooSP.zip"
+        
+                                   
       - uses: "marvinpinto/action-automatic-releases@latest"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
