Update master_build.yml
- Add check version and merge for PR into Main if appropriate
- Add automatic pre-release depending on running branch.

diff --git a/.github/workflows/master_build.yml b/.github/workflows/master_build.yml
--- a/.github/workflows/master_build.yml
+++ b/.github/workflows/master_build.yml
@@ -2,7 +2,7 @@ name: Master_Build
 
 on:
   push:
-    branches: [ "main", "Development" ]
+    branches: [ "main", "Development", "Feature_ImprovedMasterBuild"]
   #workflow_run:
   #  workflows: ["MSBuild"]
   #  types:
@@ -23,8 +23,53 @@ permissions:
   contents: read
 
 jobs:
+  check-version-and-merge:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Extract version from macros.h
+        id: extract_version
+        run: |
+          VERSION=$(grep '#define MENYOO_CURRENT_VER_' Solution/source/macros.h | awk '{print $3}' | tr -d '"')
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "Extracted version: $VERSION"
+      
+      - name: Check version pattern and merge
+        id: check_version
+        run: |
+          VERSION=${{ env.VERSION }}
+          echo "Checking version pattern: $VERSION"
+          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
+            echo "Already on main branch. Skipping merge check."
+            exit 0
+          fi
+          if [[ $VERSION =~ ^\d+\.\d+\.\d+$ ]]; then
+            echo "Version is a full release. Creating pull request to merge into main."
+            echo "## Check for existing PR"
+            if gh pr list --head development --base main --state open --json number --jq .[0].number; then
+              echo "PR already exists."
+              exit 0
+            fi
+            echo "Creating new PR."
+            gh pr create --title "Release $VERSION" --body "Merging development into main for release $VERSION" --base main --head development
+            exit 1
+          elif [[ $VERSION =~ ^\d+\.\d+\.\d+-(a|b|rc)\d+$ ]]; then
+            echo "Version is a pre-release. Proceeding with pre-release build."
+          else
+            echo "Version is invalid or a development version. Cancelling workflow."
+            exit 1
+          fi
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   build:
+    if: github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/Development' && needs.check-version-and-merge.outputs.VERSION != '')
     runs-on: windows-latest
+    needs: check-version-and-merge
 
     steps:
     - uses: actions/checkout@v3
@@ -104,6 +149,7 @@ jobs:
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: ${{ env.VERSION }}
-          prerelease: true
+          prerelease: ${{ github.ref_name != 'main' }}
           title: ${{ steps.version.outputs.version}}
           files: MenyooSP.zip
+          dry-run: true
